/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "navi_master.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ThrusterCommand, ThrusterCommand, AUTO)


PB_BIND(ArmCommand, ArmCommand, AUTO)


PB_BIND(Commands, Commands, AUTO)


PB_BIND(DepthResponse, DepthResponse, AUTO)


PB_BIND(CleanPressureResponse, CleanPressureResponse, AUTO)


PB_BIND(Responses, Responses, AUTO)



