/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_NAVI_MASTER_PB_H_INCLUDED
#define PB_NAVI_MASTER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ThrusterCommand {
    bool has_throttle0;
    int32_t throttle0;
    bool has_throttle1;
    int32_t throttle1;
    bool has_throttle2;
    int32_t throttle2;
    bool has_throttle3;
    int32_t throttle3;
    bool has_throttle4;
    int32_t throttle4;
    bool has_throttle5;
    int32_t throttle5;
    bool has_throttle6;
    int32_t throttle6;
    bool has_throttle7;
    int32_t throttle7;
} ThrusterCommand;

typedef struct _ArmCommand {
    int32_t value;
} ArmCommand;

typedef struct _Commands {
    bool has_msgTC;
    ThrusterCommand msgTC;
    bool has_msgAC;
    ArmCommand msgAC;
} Commands;

typedef struct _DepthResponse {
    float depth;
} DepthResponse;

typedef struct _CleanPressureResponse {
    int32_t pressure;
} CleanPressureResponse;

typedef struct _Responses {
    bool has_msgDR;
    DepthResponse msgDR;
    bool has_msgCPR;
    CleanPressureResponse msgCPR;
} Responses;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ThrusterCommand_init_default             {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ArmCommand_init_default                  {0}
#define Commands_init_default                    {false, ThrusterCommand_init_default, false, ArmCommand_init_default}
#define DepthResponse_init_default               {0}
#define CleanPressureResponse_init_default       {0}
#define Responses_init_default                   {false, DepthResponse_init_default, false, CleanPressureResponse_init_default}
#define ThrusterCommand_init_zero                {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ArmCommand_init_zero                     {0}
#define Commands_init_zero                       {false, ThrusterCommand_init_zero, false, ArmCommand_init_zero}
#define DepthResponse_init_zero                  {0}
#define CleanPressureResponse_init_zero          {0}
#define Responses_init_zero                      {false, DepthResponse_init_zero, false, CleanPressureResponse_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ThrusterCommand_throttle0_tag            1
#define ThrusterCommand_throttle1_tag            2
#define ThrusterCommand_throttle2_tag            3
#define ThrusterCommand_throttle3_tag            4
#define ThrusterCommand_throttle4_tag            5
#define ThrusterCommand_throttle5_tag            6
#define ThrusterCommand_throttle6_tag            7
#define ThrusterCommand_throttle7_tag            8
#define ArmCommand_value_tag                     1
#define Commands_msgTC_tag                       1
#define Commands_msgAC_tag                       2
#define DepthResponse_depth_tag                  1
#define CleanPressureResponse_pressure_tag       1
#define Responses_msgDR_tag                      1
#define Responses_msgCPR_tag                     2

/* Struct field encoding specification for nanopb */
#define ThrusterCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    throttle0,         1) \
X(a, STATIC,   OPTIONAL, INT32,    throttle1,         2) \
X(a, STATIC,   OPTIONAL, INT32,    throttle2,         3) \
X(a, STATIC,   OPTIONAL, INT32,    throttle3,         4) \
X(a, STATIC,   OPTIONAL, INT32,    throttle4,         5) \
X(a, STATIC,   OPTIONAL, INT32,    throttle5,         6) \
X(a, STATIC,   OPTIONAL, INT32,    throttle6,         7) \
X(a, STATIC,   OPTIONAL, INT32,    throttle7,         8)
#define ThrusterCommand_CALLBACK NULL
#define ThrusterCommand_DEFAULT NULL

#define ArmCommand_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    value,             1)
#define ArmCommand_CALLBACK NULL
#define ArmCommand_DEFAULT NULL

#define Commands_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  msgTC,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  msgAC,             2)
#define Commands_CALLBACK NULL
#define Commands_DEFAULT NULL
#define Commands_msgTC_MSGTYPE ThrusterCommand
#define Commands_msgAC_MSGTYPE ArmCommand

#define DepthResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    depth,             1)
#define DepthResponse_CALLBACK NULL
#define DepthResponse_DEFAULT NULL

#define CleanPressureResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    pressure,          1)
#define CleanPressureResponse_CALLBACK NULL
#define CleanPressureResponse_DEFAULT NULL

#define Responses_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  msgDR,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  msgCPR,            2)
#define Responses_CALLBACK NULL
#define Responses_DEFAULT NULL
#define Responses_msgDR_MSGTYPE DepthResponse
#define Responses_msgCPR_MSGTYPE CleanPressureResponse

extern const pb_msgdesc_t ThrusterCommand_msg;
extern const pb_msgdesc_t ArmCommand_msg;
extern const pb_msgdesc_t Commands_msg;
extern const pb_msgdesc_t DepthResponse_msg;
extern const pb_msgdesc_t CleanPressureResponse_msg;
extern const pb_msgdesc_t Responses_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ThrusterCommand_fields &ThrusterCommand_msg
#define ArmCommand_fields &ArmCommand_msg
#define Commands_fields &Commands_msg
#define DepthResponse_fields &DepthResponse_msg
#define CleanPressureResponse_fields &CleanPressureResponse_msg
#define Responses_fields &Responses_msg

/* Maximum encoded size of messages (where known) */
#define ArmCommand_size                          11
#define CleanPressureResponse_size               11
#define Commands_size                            103
#define DepthResponse_size                       5
#define NAVI_MASTER_PB_H_MAX_SIZE                Commands_size
#define Responses_size                           20
#define ThrusterCommand_size                     88

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
